Repository Samsung/TAU, pull requests merged in 2019-07, with the labels that each got.

#172 Remove unused custom elements module
  src/js/core/widget/customElements.js
  src/js/mobile.js
  src/js/tv.js
  src/js/wearable.js
Labels: 1.1

#200 (engine) fix for defering TAU load issue
  src/js/core/engine.js
  src/js/core/event/orientationchange.js
  src/js/core/router/Router.js
  src/js/core/widget/BaseWidget.js
  src/js/profile/wearable/widget/wearable/SwipeList.js
  tests/js/profile/wearable/widget/wearable/SwipeList/swipelist.js
Labels: 1.0

#217 (UIComponents) Fix for popup's look on the list with select mode
  examples/wearable/UIComponents/css/style.circle.css
Labels: in review

#208 UIComponents: GroupIndex has changed if all dependent checkbox are selected
  examples/mobile/UIComponents/components/list/list-select-check.js
Labels: 1.0, in review

#210 NumberPicker: Added auto width of text in Spin widget
  src/css/profile/wearable/changeable/common/spin.less
  src/js/profile/wearable/widget/wearable/Spin.js
Labels: 1.0

#212 UIComponents: removed unnecessary tag "span" from text on list
  examples/wearable/UIComponents/contents/controls/slider/index.html
Labels: 1.0

#228 (wearable) UIComponents: VirtualList with button looks wrong
  examples/wearable/UIComponents/contents/list/virtual/1line_btn.html
Labels: 1.0, in review

#226 UIComponents: Updating the page title for List/Normal list
  examples/mobile/UIComponents/components/list/normallist.html
Labels: 1.0, in review

#218 Floating Action: added press effect on vclick
  src/js/core/util/anchorHighlight.js
  src/js/profile/mobile/widget/mobile/FloatingActions.js
Labels: 1.0, in review

#236 Update examples and dist for 1.0
  examples/1.0/dist/mobile/js/tau.js
  examples/1.0/dist/mobile/js/tau.min.js
  examples/1.0/dist/mobile/theme/changeable/tau.css
  examples/1.0/dist/mobile/theme/changeable/tau.min.css
  examples/1.0/dist/mobile/theme/changeable/tau.min.template
  examples/1.0/dist/mobile/theme/changeable/tau.template
  examples/1.0/dist/wearable/js/tau.js
  examples/1.0/dist/wearable/js/tau.min.js
  examples/1.0/dist/wearable/theme/blue/tau.css
  examples/1.0/dist/wearable/theme/blue/tau.min.css
  examples/1.0/dist/wearable/theme/brown/tau.css
  examples/1.0/dist/wearable/theme/brown/tau.min.css
  examples/1.0/dist/wearable/theme/changeable/tau.css
  examples/1.0/dist/wearable/theme/changeable/tau.min.css
  examples/1.0/dist/wearable/theme/changeable/tau.min.template
  examples/1.0/dist/wearable/theme/changeable/tau.template
  examples/1.0/examples/mobile/UIComponents/components/headerfooter/header/righttext.html
  examples/1.0/examples/mobile/UIComponents/components/headerfooter/header/twotext.html
  examples/1.0/examples/mobile/UIComponents/components/list/list-select-check.js
  examples/1.0/examples/mobile/UIComponents/components/list/normallist.html
  examples/1.0/examples/wearable/UIComponents/contents/controls/slider/index.html
  examples/1.0/examples/wearable/UIComponents/contents/etc/index.html
  examples/1.0/examples/wearable/UIComponents/contents/etc/webkit.js
  examples/1.0/examples/wearable/UIComponents/contents/list/virtual/1line_btn.html
  examples/1.0/examples/wearable/UIComponents/css/style.circle.css
  examples/1.0/examples/wearable/UIComponents/index.html
Labels: 1.0, in review

#241 UIComponents: fix for cuted text in Toast popup
  examples/mobile/UIComponents/components/popup/toast.html
Labels: 1.0, in review, mobile

#243 Fix for right padding when horizontal scroll handler is active
  src/css/profile/mobile/changeable/common/scrollview.handler.less
Labels: 1.0, in review, mobile

#213 Disable pointer events popup
  src/css/profile/mobile/changeable/common/core.less
  src/css/profile/mobile/changeable/common/popup.less
  src/css/profile/wearable/changeable/common/popup.less
  src/js/core/widget/core/Page.js
  src/js/core/widget/core/Popup.js
Labels: 1.0, in review

#230 Add search feature to page with index scrollbar and floating button
  examples/mobile/UIComponents/components/navigationelements/indexscrollbar_floating_button.html
  examples/mobile/UIComponents/components/navigationelements/indexscrollbar_floating_button.js
  examples/mobile/UIComponents/css/style.css
Labels: 1.0, in review, mobile

#252 Update examples and dist for 1.0
  examples/1.0/dist/mobile/js/tau.js
  examples/1.0/dist/mobile/js/tau.min.js
  examples/1.0/dist/mobile/theme/changeable/tau.css
  examples/1.0/dist/mobile/theme/changeable/tau.min.css
  examples/1.0/dist/mobile/theme/changeable/tau.min.template
  examples/1.0/dist/mobile/theme/changeable/tau.template
  examples/1.0/dist/wearable/js/tau.js
  examples/1.0/dist/wearable/js/tau.min.js
  examples/1.0/dist/wearable/theme/blue/tau.css
  examples/1.0/dist/wearable/theme/blue/tau.min.css
  examples/1.0/dist/wearable/theme/brown/tau.css
  examples/1.0/dist/wearable/theme/brown/tau.min.css
  examples/1.0/dist/wearable/theme/changeable/tau.css
  examples/1.0/dist/wearable/theme/changeable/tau.min.css
  examples/1.0/dist/wearable/theme/changeable/tau.min.template
  examples/1.0/dist/wearable/theme/changeable/tau.template
  examples/1.0/examples/mobile/UIComponents/components/gallery/gallery.js
  examples/1.0/examples/mobile/UIComponents/components/list/gridview/gridcheck.js
  examples/1.0/examples/mobile/UIComponents/components/navigationelements/indexscrollbar_floating_button.html
  examples/1.0/examples/mobile/UIComponents/components/navigationelements/indexscrollbar_floating_button.js
  examples/1.0/examples/mobile/UIComponents/components/popup/toast.html
  examples/1.0/examples/mobile/UIComponents/css/style.css
  examples/1.0/examples/wearable/UIComponents/contents/etc/index.html
  examples/1.0/examples/wearable/UIComponents/contents/etc/webkit.js
  examples/1.0/examples/wearable/UIComponents/index.html
Labels: in review

#251 Contextual Popup: fix for popup width
  src/css/profile/mobile/changeable/common/contextpopup.less
Labels: 1.0, in review, mobile

#238 Fix for text and button overlaping on Listview
  examples/wearable/UIComponents/contents/list/arclistview/list_arclistview.html
  examples/wearable/UIComponents/css/style.circle.css
  src/css/profile/wearable/changeable/theme-circle/checkboxradio.less
  src/css/profile/wearable/changeable/theme-circle/listview.less
Labels: 1.0, in review, wearable

#246 Fix for remaining gradient effect in Marquee widget
  src/js/core/util/animation/animation.js
  src/js/core/widget/BaseWidget.js
Labels: 1.0, in review

#248 Fix for cut line of subtext on multiline list
  src/css/profile/wearable/changeable/theme-circle/listview.less
Labels: 1.0, in review, wearable

#254 [Wearable] Change list selection style
  src/css/profile/wearable/changeable/theme-circle/arclistview.less
  src/css/profile/wearable/changeable/theme-circle/listview.less
  src/css/profile/wearable/changeable/theme-circle/theme.changeable.less
Labels: 1.0, in review, wearable

#255 Display the initial state of radio checkbox
  examples/mobile/UIComponents/components/controls/radio.js
Labels: 1.0, in review, mobile

#257 Remove unused custom elemens module
  src/js/core/widget/customElements.js
  src/js/mobile.js
  src/js/wearable.js
Labels: 1.0

#258 TAU release 1.0.5
  dist/VERSION
  dist/mobile/js/tau.js
  dist/mobile/js/tau.min.js
  dist/mobile/js/tau.support-2.3.js
  dist/mobile/js/tau.support-2.3.min.js
  dist/mobile/theme/changeable/tau.css
  dist/mobile/theme/changeable/tau.min.css
  dist/mobile/theme/changeable/tau.min.template
  dist/mobile/theme/changeable/tau.template
  dist/wearable/js/tau.js
  dist/wearable/js/tau.min.js
  dist/wearable/theme/blue/tau.css
  dist/wearable/theme/blue/tau.min.css
  dist/wearable/theme/brown/tau.css
  dist/wearable/theme/brown/tau.min.css
  dist/wearable/theme/changeable/tau.circle.css
  dist/wearable/theme/changeable/tau.circle.min.css
  dist/wearable/theme/changeable/tau.circle.min.template
  dist/wearable/theme/changeable/tau.circle.template
  dist/wearable/theme/changeable/tau.css
  dist/wearable/theme/changeable/tau.min.css
  dist/wearable/theme/changeable/tau.min.template
  dist/wearable/theme/changeable/tau.template
  package.json
Labels: 1.0, in review

#205 (code.tizen.org) Fix for missed button image in examples
  examples/wearable/UIComponents/contents/controls/button/icon-button.css
  examples/wearable/UIComponents/contents/controls/button/icon-button.html
Labels: 1.0, in review
