Repository Samsung/TAU, pull requests merged in 2019-10, with the labels that each got.

#423 Make SectionChanger resizable
  src/js/core/widget/core/SectionChanger.js
Labels: 1.0, bug, in review

#426 (mobile) UIComponents: added dividers filtering for IndexScrollbar example
  examples/mobile/UIComponents/components/navigationelements/indexscrollbar_floating_button.js
Labels: 1.0, examples, in review, mobile

#428 (wearable) UIComponents: added marquee widget to title in graph example
  examples/wearable/UIComponents/contents/graphs/bar_graph.html
  examples/wearable/UIComponents/contents/graphs/dynamic_graph.html
  examples/wearable/UIComponents/contents/graphs/dynamic_graph.js
  examples/wearable/UIComponents/contents/graphs/static_graph.html
  examples/wearable/UIComponents/contents/graphs/static_graph.js
Labels: 1.1, examples, in review, wearable

#429 (mobile) TextInput: fix for postion of clear button icon in search input
  src/css/profile/mobile/changeable/common/textinput.less
Labels: 1.0, bug, in review, mobile

#430 TAU release 1.0.11
  dist/VERSION
  dist/mobile/js/tau.js
  dist/mobile/js/tau.min.js
  dist/mobile/js/tau.support-2.3.js
  dist/mobile/js/tau.support-2.3.min.js
  dist/mobile/theme/changeable/tau.css
  dist/mobile/theme/changeable/tau.min.css
  dist/mobile/theme/changeable/tau.min.template
  dist/mobile/theme/changeable/tau.template
  dist/wearable/js/tau.js
  dist/wearable/js/tau.min.js
  dist/wearable/theme/blue/tau.css
  dist/wearable/theme/blue/tau.min.css
  dist/wearable/theme/brown/tau.css
  dist/wearable/theme/brown/tau.min.css
  dist/wearable/theme/changeable/tau.css
  dist/wearable/theme/changeable/tau.min.css
  dist/wearable/theme/changeable/tau.min.template
  dist/wearable/theme/changeable/tau.template
  package.json
Labels: 1.0, in review

#431 Merge tau 1.0.11 into tau 1.1
  examples/mobile/UIComponents/components/headerfooter/bottombutton.html
  examples/mobile/UIComponents/components/navigationelements/indexscrollbar_floating_button.js
  examples/wearable/UIComponents/contents/etc/index.html
  src/css/profile/mobile/changeable/common/drawer.less
  src/css/profile/mobile/changeable/common/listview.less
  src/css/profile/mobile/changeable/common/progress.less
  src/css/profile/mobile/changeable/theme-changeable/theme.color.less
  src/css/profile/wearable/changeable/common/swipelist.less
  src/css/profile/wearable/changeable/theme-circle/listview.less
  src/js/core/util/anchorHighlight.js
  src/js/core/util/scrolling.js
  src/js/core/widget/core/Page.js
  src/js/core/widget/core/SectionChanger.js
  src/js/profile/wearable/widget/wearable/DatePicker.js
  src/js/profile/wearable/widget/wearable/NumberPicker.js
  src/js/profile/wearable/widget/wearable/Selector.js
  src/js/profile/wearable/widget/wearable/SnapListview.js
  src/js/profile/wearable/widget/wearable/TimePicker.js
Labels: 1.1, in review

#434 (util) globalize: block data loading when data has already exists
  src/js/core/util/globalize.js
Labels: 1.0, in review, mobile

#435 TAU release 1.0.12
  dist/VERSION
  dist/mobile/js/tau.js
  dist/mobile/js/tau.min.js
  dist/mobile/js/tau.support-2.3.js
  dist/mobile/js/tau.support-2.3.min.js
  dist/wearable/js/tau.js
  dist/wearable/js/tau.min.js
  package.json
Labels: 1.0, in review

#436 Merge changes from tau 1.0.12 into tau 1.1
  src/js/core/util/globalize.js
Labels: 1.1, in review

#438 (examples) UIComponents: Duplicated ID of elements causes change page issue
  examples/mobile/UIComponents/components/controls/textenveloper/index.html
  examples/mobile/UIComponents/components/headerfooter/index.html
  examples/mobile/UIComponents/components/list/index.html
  examples/mobile/UIComponents/components/multimediaview/index.html
  examples/mobile/UIComponents/components/navigationelements/index.html
  examples/mobile/UIComponents/components/popup/index.html
  examples/mobile/UIComponents/components/recommendations/index.html
Labels: 1.0, 1.1, in review

#439 TAU release 1.0.13
  dist/VERSION
  dist/mobile/js/tau.js
  dist/mobile/js/tau.min.js
  dist/mobile/js/tau.support-2.3.js
  dist/mobile/js/tau.support-2.3.min.js
  dist/wearable/js/tau.js
  dist/wearable/js/tau.min.js
  package.json
Labels: 1.0, 1.1, in review

#440 Merge changes from tau 1.0.13 into tau 1.1
  dist/wearable/js/tau.js
  examples/mobile/UIComponents/components/controls/textenveloper/index.html
  examples/mobile/UIComponents/components/headerfooter/index.html
  examples/mobile/UIComponents/components/list/index.html
  examples/mobile/UIComponents/components/multimediaview/index.html
  examples/mobile/UIComponents/components/navigationelements/index.html
  examples/mobile/UIComponents/components/popup/index.html
  examples/mobile/UIComponents/components/recommendations/index.html
Labels: 1.1, in review

#437 TAU release 1.1.6
  dist/VERSION
  dist/mobile/js/tau.js
  dist/mobile/js/tau.min.js
  dist/mobile/js/tau.support-2.3.js
  dist/mobile/js/tau.support-2.3.min.js
  dist/mobile/theme/changeable/tau.css
  dist/mobile/theme/changeable/tau.min.css
  dist/tv/js/tau.js
  dist/tv/js/tau.min.js
  dist/tv/theme/changeable/tau.css
  dist/tv/theme/changeable/tau.min.css
  dist/wearable/js/tau.js
  dist/wearable/js/tau.min.js
  dist/wearable/theme/blue/tau.css
  dist/wearable/theme/blue/tau.min.css
  dist/wearable/theme/brown/tau.css
  dist/wearable/theme/brown/tau.min.css
  dist/wearable/theme/changeable/tau.circle.css
  dist/wearable/theme/changeable/tau.circle.min.css
  dist/wearable/theme/changeable/tau.css
  dist/wearable/theme/changeable/tau.min.css
  package.json
Labels: 1.1, in review

#443 (examples) UIComponents: fix for header height in DatePicker sample
  examples/wearable/UIComponents/contents/controls/date-picker.html
Labels: 1.0, 1.1, bug, examples, in review, wearable

#444 (core) BaseWidget: fix for converting number options during widget refresh
  examples/wearable/UIComponents/contents/controls/time-picker.html
  src/js/core/widget/BaseWidget.js
  src/js/profile/wearable/widget/wearable/TimePicker.js
Labels: 1.0, 1.1, bug, important, mobile, wearable

#442 (examples) UIComponents: fix for webkit date/time inputs appearance
  examples/wearable/UIComponents/contents/etc/index.html
  examples/wearable/UIComponents/css/style.circle.css
Labels: 1.0, 1.1, bug, examples, in review, wearable

#446 TAU release 1.0.14
  dist/VERSION
  dist/mobile/js/tau.js
  dist/mobile/js/tau.min.js
  dist/mobile/js/tau.support-2.3.js
  dist/mobile/js/tau.support-2.3.min.js
  dist/wearable/js/tau.js
  dist/wearable/js/tau.min.js
  package.json
Labels: 1.0, in review

#447 Tau 1.1.7 release
  dist/VERSION
  dist/mobile/js/tau.js
  dist/mobile/js/tau.min.js
  dist/mobile/js/tau.support-2.3.js
  dist/mobile/js/tau.support-2.3.min.js
  dist/tv/js/tau.js
  dist/tv/js/tau.min.js
  dist/wearable/js/tau.js
  dist/wearable/js/tau.min.js
  examples/wearable/UIComponents/contents/controls/date-picker.html
  examples/wearable/UIComponents/contents/controls/time-picker.html
  examples/wearable/UIComponents/contents/etc/index.html
  examples/wearable/UIComponents/css/style.circle.css
  package.json
  src/js/profile/wearable/widget/wearable/TimePicker.js
Labels: 1.1, in review

#451 PageContainer: fix for options object delivered to the change method
  src/js/core/widget/core/PageContainer.js
Labels: 1.1, bug, in review, wearable

#452 TAU release 1.1.8
  dist/VERSION
  dist/mobile/js/tau.js
  dist/mobile/js/tau.min.js
  dist/mobile/js/tau.support-2.3.js
  dist/mobile/js/tau.support-2.3.min.js
  dist/tv/js/tau.js
  dist/tv/js/tau.min.js
  dist/wearable/js/tau.js
  dist/wearable/js/tau.min.js
  package.json
Labels: 1.1

#461 (wearable) Spin: added widget example for using in public api
  examples/wearable/UIComponents/contents/controls/index.html
  examples/wearable/UIComponents/contents/controls/spin/custom-spin.html
  examples/wearable/UIComponents/contents/controls/spin/default-spin.html
  examples/wearable/UIComponents/contents/controls/spin/index.html
  examples/wearable/UIComponents/contents/controls/spin/js/custom-spin.js
  examples/wearable/UIComponents/contents/controls/spin/js/default-spin.js
  examples/wearable/UIComponents/contents/controls/spin/js/spin-group.js
  examples/wearable/UIComponents/contents/controls/spin/spin-group.html
  src/js/core/widget/BaseWidget.js
  src/js/profile/wearable/widget/wearable/Spin.js
  tests/js/profile/wearable/widget/wearable/CircularIndexScrollbar/circularindexscrollbar.js
Labels: 1.0, 1.1, in review
