Repository Samsung/TAU, pull requests merged in 2019-11, with the labels that each got.

#468 Remove text scale effect on press in footer button
  src/css/profile/wearable/changeable/theme-circle/layout.less
Labels: 1.0, in review

#470 TimePicker: fix for widget getValue method
  src/js/profile/wearable/widget/wearable/TimePicker.js
Labels: 1.0, bug, in review

#471 Util: _loop method provides loop Time for current animation frame
  src/js/core/util.js
Labels: 1.0, bug

#472 TAU release 1.0.16
  dist/VERSION
  dist/mobile/js/tau.js
  dist/mobile/js/tau.min.js
  dist/mobile/js/tau.support-2.3.js
  dist/mobile/js/tau.support-2.3.min.js
  dist/wearable/js/tau.js
  dist/wearable/js/tau.min.js
  dist/wearable/theme/changeable/tau.circle.css
  dist/wearable/theme/changeable/tau.circle.min.css
  dist/wearable/theme/changeable/tau.circle.min.template
  dist/wearable/theme/changeable/tau.circle.template
  package.json
Labels: 1.0, in review

#473 Merge changes from TAU 1.0 into TAU 1.1
  dist/wearable/js/tau.js
  dist/wearable/theme/changeable/tau.circle.css
  examples/wearable/UIComponents/contents/controls/index.html
  examples/wearable/UIComponents/contents/controls/spin/custom-spin.html
  examples/wearable/UIComponents/contents/controls/spin/default-spin.html
  examples/wearable/UIComponents/contents/controls/spin/index.html
  examples/wearable/UIComponents/contents/controls/spin/js/custom-spin.js
  examples/wearable/UIComponents/contents/controls/spin/js/default-spin.js
  examples/wearable/UIComponents/contents/controls/spin/js/spin-group.js
  examples/wearable/UIComponents/contents/controls/spin/spin-group.html
  src/css/profile/wearable/changeable/theme-circle/layout.less
  src/js/core/util.js
  src/js/core/widget/BaseWidget.js
  src/js/core/widget/core/Page.js
  src/js/core/widget/core/scroller/scrollbar/ScrollBar.js
  src/js/profile/wearable/widget/wearable/Spin.js
  src/js/profile/wearable/widget/wearable/TimePicker.js
  tests/js/profile/wearable/widget/wearable/CircularIndexScrollbar/circularindexscrollbar.js
Labels: 1.1, in review

#479 Fix resetting marquee element
  src/js/core/widget/BaseWidget.js
  src/js/core/widget/core/Marquee.js
  tests/js/core/widget/core/Marquee/Marquee.js
Labels: 1.0, bug

#482 TAU release 1.0.17
  dist/VERSION
  dist/mobile/js/tau.js
  dist/mobile/js/tau.min.js
  dist/mobile/js/tau.support-2.3.js
  dist/mobile/js/tau.support-2.3.min.js
  dist/wearable/js/tau.js
  dist/wearable/js/tau.min.js
  package.json
Labels: 1.0, in review

#492 Marquee: fix for wrong marquee position after reset
  examples/wearable/UIComponents/contents/list/list_marquee_style.js
  src/js/core/util.js
  src/js/core/util/animation/animation.js
  src/js/core/widget/BaseWidget.js
  src/js/core/widget/core/Marquee.js
  tests/js/core/widget/core/Marquee/Marquee.js
Labels: 1.0, 1.1, 1.2, in review

#495 TAU release 1.0.18
  dist/VERSION
  dist/mobile/js/tau.js
  dist/mobile/js/tau.min.js
  dist/mobile/js/tau.support-2.3.js
  dist/mobile/js/tau.support-2.3.min.js
  dist/wearable/js/tau.js
  dist/wearable/js/tau.min.js
  package.json
Labels: 1.0, in review
