Repository Samsung/TAU, pull requests merged in 2019-05, with the labels that each got.

#93 Fix spellchecking errors and enable spellcheck for every commit
  .travis.yml
  package.json
  src/js/core/history/manager.js
  src/js/profile/mobile/widget/mobile/Listview.js
  src/js/profile/wearable/widget/wearable/ArcListview.js
Labels: 4.0

#110 Listview: fix for overlapping text and checkbox
  src/css/profile/mobile/changeable/common/groupindex.less
Labels: 4.0, bug

#105 Virtual Listview: fix for missing items on list
  examples/mobile/UIComponents/components/list/virtuallist.html
  examples/mobile/UIComponents/components/list/virtuallist_normal.html
  src/js/core/widget/core/VirtualListview.js
Labels: 4.0, bug

#114 (mobile) Listview: Sometime colored listview doesn't refresh
  src/js/profile/mobile/widget/mobile/Listview.js
Labels: 4.0, bug

#120 Fix for Radio button position on listview with group index
  src/css/profile/mobile/changeable/common/groupindex.less
Labels: 4.0, bug

#123 DropDownMenu: fix for duplicates wrapper layer on refresh
  src/js/profile/mobile/widget/mobile/DropdownMenu.js
Labels: 4.0, bug

#124 Change padding for list item after list group index
  src/css/profile/mobile/changeable/common/groupindex.less
Labels: 4.0, bug

#127 TAU release 1.0.1
  dist/VERSION
  dist/mobile/js/tau.js
  dist/mobile/js/tau.min.js
  dist/mobile/js/tau.support-2.3.js
  dist/mobile/js/tau.support-2.3.min.js
  dist/mobile/theme/changeable/tau.css
  dist/mobile/theme/changeable/tau.min.css
  dist/mobile/theme/changeable/tau.min.template
  dist/mobile/theme/changeable/tau.template
  dist/wearable/js/tau.js
  dist/wearable/js/tau.min.js
  package.json
Labels: 1.0
