Repository Samsung/TAU, pull requests merged in 2019-09, with the labels that each got.

#346 Fix graph plot color property
  src/js/core/widget/core/Graph.js
Labels: 1.0, DE, bug, in review

#349 FloatingActions: fix for button width
  src/css/profile/mobile/changeable/common/floatingactions.less
Labels: 1.0, 1.1, bug, in review

#328 Graph: added unit tests
  .eslintignore
  src/js/core/widget/core/Graph.js
  tests/js/core/widget/core/Graph/Graph.html
  tests/js/core/widget/core/Graph/Graph.js
  tests/libs/es6-collections.js
Labels: 1.1, in review

#351 engine: add getBinding instance search on widget wrapper
  src/js/core/engine.js
Labels: 1.0, 1.1, in review

#352 DropDownMenu: update placeholder on widget refresh
  src/js/core/widget/BaseWidget.js
  src/js/profile/mobile/widget/mobile/DropdownMenu.js
  tests/js/profile/mobile/widget/mobile/DropdownMenu/DropdownMenu.js
Labels: 1.0, 1.1, bug, dependent

#363 Add common files to tct test packages
  tests/js/core/widget/core/Graph/Graph.html
  tools/grunt/tasks/tests.js
Labels: 1.1, bug, in review

#359 Events/vmouse: method handleTouchMove doesn't ready for broken data
  src/js/core/event/vmouse.js
Labels: 1.1, in review

#361 (tct) Change version of TCT to 5.5
  tests/tct-paker.sh
  tools/grunt/tasks/tau-tct.js
Labels: 1.1, in review

#362 (tests) RadioButton & Checkbox: fix for depracated API synchronous XHTTPRequest
  tests/js/core/widget/core/Checkbox/api/Checkbox.html
  tests/js/core/widget/core/Checkbox/api/Checkbox.js
  tests/js/core/widget/core/Radio/api/Radio.html
  tests/js/core/widget/core/Radio/api/Radio.js
Labels: 1.1, in review

#365 Utils: Added copy of attributes from original inline script to new one
  src/js/core/util.js
Labels: 1.1, in review

#370 TAU release 1.1.4
  dist/VERSION
  dist/libs/jquery.flipster.min.js
  dist/mobile/js/tau.bundle.js
  dist/mobile/js/tau.js
  dist/mobile/js/tau.min.js
  dist/mobile/js/tau.support-2.3.js
  dist/mobile/js/tau.support-2.3.min.js
  dist/mobile/theme/changeable/tau.css
  dist/mobile/theme/changeable/tau.min.css
  dist/tv/js/tau.bundle.min.js
  dist/tv/js/tau.js
  dist/tv/js/tau.min.js
  dist/tv/theme/changeable/tau.css
  dist/tv/theme/changeable/tau.min.css
  dist/wearable/js/tau.bundle.js
  dist/wearable/js/tau.js
  dist/wearable/js/tau.min.js
  dist/wearable/theme/blue/tau.css
  dist/wearable/theme/blue/tau.min.css
  dist/wearable/theme/brown/tau.css
  dist/wearable/theme/brown/tau.min.css
  dist/wearable/theme/changeable/tau.css
  dist/wearable/theme/changeable/tau.min.css
  package.json
Labels: 1.1, in review

#371 SnapListview: scroll issue
  src/css/profile/wearable/changeable/theme-circle/layout.less
  src/css/profile/wearable/changeable/theme-circle/listview.less
  src/js/core/util/scrolling.js
  src/js/profile/wearable/widget/wearable/SnapListview.js
Labels: 1.0, 1.1, bug, in review, wearable

#373 Change snaplist press effect background color
  src/css/profile/wearable/changeable/theme-circle/theme.changeable.less
Labels: 1.0, 1.1

#375 SnapListview: scrolling issue when list has deviders (patch from branch 1.1)
  src/css/profile/wearable/changeable/theme-circle/layout.less
  src/css/profile/wearable/changeable/theme-circle/listview.less
  src/js/core/util/scrolling.js
  src/js/profile/wearable/widget/wearable/SnapListview.js
Labels: 1.0, bug

#376 TAU release 1.0.7
  dist/VERSION
  dist/common/js/tau.flipster.js
  dist/common/js/tau.flipster.min.js
  dist/common/js/tau.graphs.js
  dist/common/js/tau.graphs.min.js
  dist/common/js/tau.i3d.js
  dist/common/js/tau.i3d.min.js
  dist/mobile/js/tau.js
  dist/mobile/js/tau.min.js
  dist/mobile/js/tau.support-2.3.js
  dist/mobile/js/tau.support-2.3.min.js
  dist/mobile/theme/changeable/tau.css
  dist/mobile/theme/changeable/tau.min.css
  dist/mobile/theme/changeable/tau.min.template
  dist/mobile/theme/changeable/tau.template
  dist/wearable/js/tau.js
  dist/wearable/js/tau.min.js
  dist/wearable/theme/changeable/tau.circle.css
  dist/wearable/theme/changeable/tau.circle.min.css
  dist/wearable/theme/changeable/tau.circle.min.template
  dist/wearable/theme/changeable/tau.circle.template
  package.json
Labels: 1.0

#377 Remove unnecessary common folder
  dist/common/js/tau.flipster.js
  dist/common/js/tau.flipster.min.js
  dist/common/js/tau.graphs.js
  dist/common/js/tau.graphs.min.js
  dist/common/js/tau.i3d.js
  dist/common/js/tau.i3d.min.js
Labels: 1.0

#379 Add writable property check for object merge method
  src/js/core/util/object.js
Labels: 1.0, 1.1, in review

#378 SwipeListview: fast scroll issue & overscroll issue
  src/js/core/util/scrolling.js
  src/js/profile/wearable/widget/wearable/SnapListview.js
Labels: 1.0, 1.1, important, in progress

#381 TAU release 1.0.8
  dist/VERSION
  dist/mobile/js/tau.js
  dist/mobile/js/tau.min.js
  dist/mobile/js/tau.support-2.3.js
  dist/mobile/js/tau.support-2.3.min.js
  dist/wearable/js/tau.js
  dist/wearable/js/tau.min.js
  package.json
Labels: 1.0, in review

#382 Merge tau 1.0.7 into tau 1.1.4
  dist/mobile/js/tau.js
  dist/tv/theme/changeable/tau.css
  src/css/profile/wearable/changeable/theme-circle/theme.changeable.less
  src/js/core/util/object.js
  src/js/core/util/scrolling.js
  src/js/profile/wearable/widget/wearable/SnapListview.js
Labels: 1.1, in review

#396 (wearable) SnapListview: reverting change of column layout in LI item
  src/css/profile/wearable/changeable/theme-circle/listview.less
Labels: 1.0, in review

#395 Scrolling: Reset current index for snap point list
  src/js/core/util/scrolling.js
Labels: 1.0, in review

#400 TAU release 1.0.9
  dist/VERSION
  dist/mobile/js/tau.js
  dist/mobile/js/tau.min.js
  dist/mobile/js/tau.support-2.3.js
  dist/mobile/js/tau.support-2.3.min.js
  dist/wearable/js/tau.js
  dist/wearable/js/tau.min.js
  dist/wearable/theme/changeable/tau.circle.css
  dist/wearable/theme/changeable/tau.circle.min.css
  dist/wearable/theme/changeable/tau.circle.min.template
  dist/wearable/theme/changeable/tau.circle.template
  package.json
Labels: 1.0, in review

#403 TAU release 1.0.10
  dist/VERSION
  dist/mobile/js/tau.js
  dist/mobile/js/tau.min.js
  dist/mobile/js/tau.support-2.3.js
  dist/mobile/js/tau.support-2.3.min.js
  dist/wearable/js/tau.js
  dist/wearable/js/tau.min.js
  package.json
Labels: 1.0, in review

#410 Add missing btn-text class for button
  examples/wearable/UIComponents/contents/etc/index.html
Labels: 1.0, in review

#414 Change positioning of swipelist item text and icon
  src/css/profile/wearable/changeable/common/swipelist.less
Labels: 1.0, 1.1, bug, in review, wearable

#412 Expandalbe list: apply active state only for it's header
  src/css/profile/mobile/changeable/common/listview.less
Labels: 1.0, in review

#390 (wearable) Number, Time and Date pickers: remove "set" button on widget destroy
  src/js/profile/wearable/widget/wearable/DatePicker.js
  src/js/profile/wearable/widget/wearable/NumberPicker.js
  src/js/profile/wearable/widget/wearable/TimePicker.js
Labels: 1.0, 1.1, in review

#416 UIComponents: fix for duplicate page ID in bottom button example
  examples/mobile/UIComponents/components/headerfooter/bottombutton.html
Labels: 1.0, 1.1, bug, examples, in review

#418 Page: storing and restoring page scroll position on page change
  src/js/core/widget/core/Page.js
Labels: 1.0, 1.1, in review, mobile

#422 (mobile) Drawer: fix for filling colored list in drawer widget
  src/css/profile/mobile/changeable/common/drawer.less
  src/css/profile/mobile/changeable/theme-changeable/theme.color.less
Labels: 1.0, bug, in review, mobile

#420 Highlight: fix for two items highlights in the same time
  src/js/core/util/anchorHighlight.js
Labels: 1.0, bug, in review, mobile
