Repository Samsung/TAU, pull requests merged in 2020-01, with the labels that each got.

#531 Spin: Event "spinchange" has stopped when widget is in disabled state
  src/js/profile/wearable/widget/wearable/Spin.js
Labels: 1.0

#522 fixup: Fix problem that scrollToPosition is not working correctly
  src/js/core/util/scrolling.js
  src/js/profile/wearable/widget/wearable/SnapListview.js
Labels: 1.0, in review

#532 Page, ArcListview: Changing scroll position of hidden page
  src/js/core/widget/core/Page.js
  src/js/profile/wearable/widget/wearable/ArcListview.js
Labels: 1.0, in review

#525 Marquee: fix for animation type endToEnd
  examples/wearable/UIComponents/contents/controls/marquee/index.html
  examples/wearable/UIComponents/contents/controls/marquee/marquee.js
  src/css/profile/wearable/changeable/common/marquee.less
  src/css/profile/wearable/changeable/theme-circle/marquee.less
  src/js/core/widget/core/Marquee.js
  tests/js/core/widget/core/Marquee/Marquee.js
Labels: 1.0, in review

#537 TAU release 1.0.22
  dist/VERSION
  dist/mobile/js/tau.js
  dist/mobile/js/tau.min.js
  dist/mobile/js/tau.support-2.3.js
  dist/mobile/js/tau.support-2.3.min.js
  dist/mobile/theme/changeable/tau.css
  dist/mobile/theme/changeable/tau.min.css
  dist/mobile/theme/changeable/tau.min.template
  dist/mobile/theme/changeable/tau.template
  dist/wearable/js/tau.js
  dist/wearable/js/tau.min.js
  dist/wearable/theme/blue/tau.css
  dist/wearable/theme/blue/tau.min.css
  dist/wearable/theme/brown/tau.css
  dist/wearable/theme/brown/tau.min.css
  dist/wearable/theme/changeable/tau.circle.css
  dist/wearable/theme/changeable/tau.circle.min.css
  dist/wearable/theme/changeable/tau.circle.min.template
  dist/wearable/theme/changeable/tau.circle.template
  dist/wearable/theme/changeable/tau.css
  dist/wearable/theme/changeable/tau.min.css
  dist/wearable/theme/changeable/tau.min.template
  dist/wearable/theme/changeable/tau.template
  package.json
Labels: 1.0, in review

#556 (util) rotaryScrolling: added new methods for lock/unclock of scrolling
  examples/wearable/UIComponents/contents/controls/marquee/index.html
  examples/wearable/UIComponents/js/circle-helper.js
  src/js/core/util/rotaryScrolling.js
  src/js/core/widget/core/SectionChanger.js
  src/js/core/widget/core/VirtualListview.js
  src/js/profile/wearable/widget/wearable/ArcListview.js
  src/js/profile/wearable/widget/wearable/Grid.js
  src/js/profile/wearable/widget/wearable/Slider.js
  src/js/profile/wearable/widget/wearable/SnapListview.js
  src/js/profile/wearable/widget/wearable/Spin.js
Labels: 1.0

#557 UIComponents: fix for circle-helper for support bezel in popup content
  examples/wearable/UIComponents/js/circle-helper.js
Labels: 1.0

#559 Marquee: Deprecated value 'ellipsis' for option 'ellipsisEffect'
  examples/wearable/UIComponents/contents/controls/marquee/index.html
  src/js/core/widget/core/Marquee.js
Labels: 1.0, in review

#562 (UIComponents) SnapListView: fix for wrong selection on rotary scrolling
  examples/wearable/UIComponents/js/circle-helper.js
Labels: 1.0, examples, in review

#560 ArcListview: fix for selection highlight
  src/js/profile/wearable/widget/wearable/ArcListview.js
Labels: 1.0, in review

#565 IndexScrollbar: fix for scroll to select index
  examples/wearable/UIComponents/contents/navcontrols/indexscrollbar/indexScrollbar.js
  src/css/profile/wearable/changeable/theme-circle/circularindexscrollbar.less
  src/js/profile/wearable/widget/wearable/ArcListview.js
  src/js/profile/wearable/widget/wearable/CircularIndexScrollbar.js
Labels: 1.0, in review
