Repository Samsung/TAU, pull requests merged in 2020-02, with the labels that each got.

#586 (SVACE) Gruntfile: fix for unconsistently "return" use
  Gruntfile.js
Labels: 1.0, in review

#587 (SVACE) engine.js: fix expression for element always evaluate to true
  src/js/core/engine.js
Labels: 1.0, in review, svace

#595 (SVACE) Scrollview: add return at the end of findPositionAnchor method
  src/js/core/widget/core/Scrollview.js
Labels: 1.0, in review, svace

#598 (SVACE) Progress: define step function
  src/js/core/widget/core/progress/Progress.js
Labels: 1.0, in review, svace

#589 (SVACE) engine: Refactoring of events handler to anonymous function
  src/js/core/engine.js
Labels: 1.0, in review, svace

#590 (SVACE) vmouse: added 'return' on end of function
  src/js/core/event/vmouse.js
Labels: 1.0, in review, svace

#599 (SVACE) ArcListview: use "return" consistently
  src/js/profile/wearable/widget/wearable/ArcListview.js
Labels: 1.0, in review, svace

#591 (SVACE) history manager: fix for expression evaluated always true
  src/js/core/history/manager.js
Labels: 1.0, in review, svace

#593 (SVACE) support: remove redundant assignment for pointerEvents
  src/js/core/support.js
Labels: 1.0, in review, svace

#594 (SVACE) BaseWidget: added "return" at the end of "trigger" methods
  src/js/core/widget/BaseWidget.js
Labels: 1.0, in review, svace

#596 (SVACE) PageIndicator: the option "intervalAngle" must be a number
  src/js/core/widget/core/PageIndicator.js
Labels: 1.0, in review, svace

#597 (SVACE) Scroller: removing redundant assignment
  src/js/core/widget/core/scroller/Scroller.js
Labels: 1.0, in review, svace

#600 (SVACE) RotaryEventBinder: removing name from animation function
  src/js/profile/wearable/helper/RotaryEventBinder.js
Labels: 1.0, in review, svace

#603 (SVACE) performance: add return at the end of get function
  src/js/tools/performance.js
Labels: 1.0, in review, svace

#604 (SVACE) FastScroll: removed unreached parts of code
  src/js/support/mobile/widget/Fastscroll.js
Labels: 1.0, in review, svace

#609 (SVACE) Datetimepicker: omit number conversion to string
  src/js/support/mobile/widget/Datetimepicker.js
Labels: 1.0, in review, svace

#605 (SVACE) ToggleSwitch.extra: remove unreachable code
  src/js/support/mobile/widget/ToggleSwitch.extra.js
Labels: 1.0, in review, svace

#602 (SVACE) Slider: added "return" to "_setValue" method
  src/js/profile/wearable/widget/wearable/Slider.js
Labels: 1.0, in review, svace

#611 (SVACE) SearchBar: remove unnecessary code
  src/js/support/mobile/widget/SearchBar.js
Labels: 1.0, in review, svace

#612 TAU release 1.0.25
  package.json
Labels: 1.0, in review

#614 TAU 1.1.14 release
  package.json
Labels: 1.1, in review

#616 TAU 1.1.15 release
  package.json
Labels: 1.1, in review

#626 (tests) Page: update for tests of Title in AppBar
  tests/js/core/widget/core/Page/Page.js
  tests/js/core/widget/core/Page/mobile/page.js
Labels: 1.2

#633 (tests) Fixing of Slider's failing tests
  tests/js/core/widget/core/Slider/Slider.js
  tests/js/core/widget/core/Slider/api/slider.js
Labels: 1.2

#635 (styles) Defining color palette and replacing components colors
  src/css/profile/wearable/changeable/theme-circle/layout.less
  src/css/profile/wearable/changeable/theme-circle/popup.less
  src/css/profile/wearable/changeable/theme-circle/theme.changeable.less
  src/css/profile/wearable/changeable/theme-circle/theme.colorPalette.less
  src/css/profile/wearable/changeable/theme-circle/toggleswitch.less
Labels: 1.2, in review

#651 Add long title on list example
  examples/wearable/UIComponents/contents/navigationelements/titlebar/index.html
  examples/wearable/UIComponents/contents/navigationelements/titlebar/long-title-subtitle-on-list.html
Labels: 1.2, in review

#618 Add/coverage api
  package-lock.json
  package.json
  tests/karma/all.conf.js
  tests/karma/single.conf.js
  tests/karma/testPaths.js
  tests/karma/uicomponents.mobile.conf.js
  tests/karma/uicomponents.wearable.conf.js
  tools/grunt/tasks/generate-api-coverage-info/index.js
Labels: 1.2, in review

#655 IndexScrollbar: updating according to guideline
  src/css/profile/wearable/changeable/common/circularindexscrollbar.less
  src/css/profile/wearable/changeable/theme-circle/theme.changeable.less
Labels: 1.2

#660 TAU release 1.0.26
  package.json
Labels: 1.0, in review

#662 Scrollview: implement vertical-horizontal bouncing
  src/js/profile/wearable/widget/wearable/Scrollview.js
Labels: 1.2, in review

#672 Use direct parameter to set scrolled on true in case of rotary event
  src/js/core/widget/core/SectionChanger.js
Labels: 1.0, in review

#647 FastScroll: ScrollHandler for wearable profile
  examples/wearable/UIComponents/contents/navigationelements/fastscroll.html
  examples/wearable/UIComponents/contents/navigationelements/fastscroll.js
  examples/wearable/UIComponents/contents/navigationelements/index.html
  examples/wearable/UIComponents/js/circle-helper.js
  src/css/profile/wearable/changeable/theme-changeable/images/indicator_fast_scroll_arrow.png
  src/css/profile/wearable/changeable/theme-changeable/images/indicator_fast_scroll_bg.png
  src/css/profile/wearable/changeable/theme-changeable/theme.circle.less
  src/css/profile/wearable/changeable/theme-circle/scrollview.handler.less
  src/css/profile/wearable/changeable/theme-circle/theme.changeable.less
  src/css/profile/wearable/changeable/theme-circle/theme.colorPalette.less
  src/js/core/widget/core/ScrollHandler.js
  src/js/mobile.js
  src/js/tv.js
  src/js/wearable.js
Labels: 1.2, in progress

#656 Assist Panel: Button and showing assist panel
  examples/wearable/UIComponents/contents/navigationelements/assist-panel.html
  examples/wearable/UIComponents/contents/navigationelements/assist-panel.js
  examples/wearable/UIComponents/contents/navigationelements/drawer.html
  examples/wearable/UIComponents/contents/navigationelements/drawer.js
  examples/wearable/UIComponents/contents/navigationelements/index.html
  examples/wearable/UIComponents/js/circle-helper.js
  src/css/profile/wearable/changeable/theme-changeable/images/primary_assist_btn.png
  src/css/profile/wearable/changeable/theme-changeable/theme.circle.less
  src/css/profile/wearable/changeable/theme-circle/assistpanel.less
  src/js/core/widget/core/Drawer.js
  src/js/profile/wearable/widget/wearable/AssistPanel.js
  src/js/wearable.js
Labels: 1.2, wearable
